
const data_imgs = [
  {
    link: "/assets/images/gallery/1.jpeg",
    src: "/assets/images/gallery/1.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Hurdlemania Aquatic",
  },
  {
    link: "/assets/images/gallery/2.jpeg",
    src: "/assets/images/gallery/2.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Hurdlemania Ground",
  },
  {
    link: "/assets/images/gallery/3.jpeg",
    src: "/assets/images/gallery/3.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Hurdlemania Aquatic",
  },
  {
    link: "/assets/images/gallery/4.jpeg",
    src: "/assets/images/gallery/4.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Line Folower Robot",
  },
  {
    link: "/assets/images/gallery/5.jpeg",
    src: "/assets/images/gallery/5.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Interactive Sessions",
  },
  {
    link: "/assets/images/gallery/6.jpeg",
    src: "/assets/images/gallery/6.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Interactive Sessions",
  },
  {
    link: "/assets/images/gallery/7.jpeg",
    src: "/assets/images/gallery/7.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Line Folower Robot",
  },
  {
    link: "/assets/images/gallery/8.jpeg",
    src: "/assets/images/gallery/9.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Interactive Sessions",
  },
  {
    link: "/assets/images/gallery/10.jpeg",
    src: "/assets/images/gallery/10.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Robo FootBall",
  },
  {
    link: "/assets/images/gallery/11.jpeg",
    src: "/assets/images/gallery/11.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Interactive Sessions",
  },
  {
    link: "/assets/images/gallery/12.jpeg",
    src: "/assets/images/gallery/12.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Robo FootBall",
  },
  {
    link: "/assets/images/gallery/13.jpeg",
    src: "/assets/images/gallery/13.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Electro Maze",
  },
  {
    link: "/assets/images/gallery/14.jpeg",
    src: "/assets/images/gallery/14.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Interactive Sessions",
  },
  {
    link: "/assets/images/gallery/15.jpeg",
    src: "/assets/images/gallery/15.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Electro Maze",
  },
  {
    link: "/assets/images/gallery/16.jpeg",
    src: "/assets/images/gallery/16.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Robo Football",
  },
  {
    link: "/assets/images/gallery/17.jpeg",
    src: "/assets/images/gallery/17.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Robo Football",
  },
  {
    link: "/assets/images/gallery/18.jpeg",
    src: "/assets/images/gallery/18.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Electro Maze",
  },
  {
    link: "/assets/images/gallery/19.jpeg",
    src: "/assets/images/gallery/19.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Hurdlemania Ground",
  },
  {
    link: "/assets/images/gallery/20.jpeg",
    src: "/assets/images/gallery/20.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Hurdlemania Ground",
  },
  {
    link: "/assets/images/gallery/21.jpeg",
    src: "/assets/images/gallery/21.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Hurdlemania Ground",
  },
  {
    link: "/assets/images/gallery/22.jpeg",
    src: "/assets/images/gallery/22.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Hurdlemania Aquatic",
  },
  {
    link: "/assets/images/gallery/23.jpeg",
    src: "/assets/images/gallery/23.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Hurdlemania Ground",
  },
  {
    link: "/assets/images/gallery/24.jpeg",
    src: "/assets/images/gallery/24.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Induction of Students",
  },
  {
    link: "/assets/images/gallery/25.jpeg",
    src: "/assets/images/gallery/25.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Induction of Students",
  },
  {
    link: "/assets/images/gallery/26.jpeg",
    src: "/assets/images/gallery/26.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Air Projects",
  },
  {
    link: "/assets/images/gallery/27.jpeg",
    src: "/assets/images/gallery/27.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Induction of Students",
  },
  {
    link: "/assets/images/gallery/28.jpeg",
    src: "/assets/images/gallery/28.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Induction of Students",
  },
  {
    link: "/assets/images/gallery/29.jpeg",
    src: "/assets/images/gallery/29.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Demonstration of Air Projects",
  },
  {
    link: "/assets/images/gallery/30.jpeg",
    src: "/assets/images/gallery/30.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Induction of Students",
  },
  {
    link: "/assets/images/gallery/31.jpeg",
    src: "/assets/images/gallery/31.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Induction of Students",
  },
  {
    link: "/assets/images/gallery/32.jpeg",
    src: "/assets/images/gallery/32.jpeg",
    alt: "Portrait by Jessica Felicio",
    caption: "Induction of Students",
  },
];

export default data_imgs;
